apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamgen-ai
  labels:
    app: streamgen-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamgen-ai
  template:
    metadata:
      labels:
        app: streamgen-ai
    spec:
      containers:
      - name: streamgen-ai
        image: paripuranam/streamgen-ai:b1cb0a5
        ports:
        - containerPort: 80